/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CaptureRouteImport } from './routes/capture'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedLearnRouteImport } from './routes/_authenticated/learn'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedJournalIndexRouteImport } from './routes/_authenticated/journal.index'
import { Route as AuthenticatedArchiveIndexRouteImport } from './routes/_authenticated/archive.index'
import { Route as AuthenticatedJournalNewRouteImport } from './routes/_authenticated/journal.new'
import { Route as AuthenticatedJournalIdRouteImport } from './routes/_authenticated/journal.$id'
import { Route as AuthenticatedArchiveNewRouteImport } from './routes/_authenticated/archive.new'
import { Route as AuthenticatedArchiveIdRouteImport } from './routes/_authenticated/archive.$id'

const CaptureRoute = CaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLearnRoute = AuthenticatedLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJournalIndexRoute =
  AuthenticatedJournalIndexRouteImport.update({
    id: '/journal/',
    path: '/journal/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedArchiveIndexRoute =
  AuthenticatedArchiveIndexRouteImport.update({
    id: '/archive/',
    path: '/archive/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedJournalNewRoute = AuthenticatedJournalNewRouteImport.update({
  id: '/journal/new',
  path: '/journal/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJournalIdRoute = AuthenticatedJournalIdRouteImport.update({
  id: '/journal/$id',
  path: '/journal/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedArchiveNewRoute = AuthenticatedArchiveNewRouteImport.update({
  id: '/archive/new',
  path: '/archive/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedArchiveIdRoute = AuthenticatedArchiveIdRouteImport.update({
  id: '/archive/$id',
  path: '/archive/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/capture': typeof CaptureRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/learn': typeof AuthenticatedLearnRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/archive/$id': typeof AuthenticatedArchiveIdRoute
  '/archive/new': typeof AuthenticatedArchiveNewRoute
  '/journal/$id': typeof AuthenticatedJournalIdRoute
  '/journal/new': typeof AuthenticatedJournalNewRoute
  '/archive/': typeof AuthenticatedArchiveIndexRoute
  '/journal/': typeof AuthenticatedJournalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/capture': typeof CaptureRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/learn': typeof AuthenticatedLearnRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/archive/$id': typeof AuthenticatedArchiveIdRoute
  '/archive/new': typeof AuthenticatedArchiveNewRoute
  '/journal/$id': typeof AuthenticatedJournalIdRoute
  '/journal/new': typeof AuthenticatedJournalNewRoute
  '/archive': typeof AuthenticatedArchiveIndexRoute
  '/journal': typeof AuthenticatedJournalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/capture': typeof CaptureRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/learn': typeof AuthenticatedLearnRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/archive/$id': typeof AuthenticatedArchiveIdRoute
  '/_authenticated/archive/new': typeof AuthenticatedArchiveNewRoute
  '/_authenticated/journal/$id': typeof AuthenticatedJournalIdRoute
  '/_authenticated/journal/new': typeof AuthenticatedJournalNewRoute
  '/_authenticated/archive/': typeof AuthenticatedArchiveIndexRoute
  '/_authenticated/journal/': typeof AuthenticatedJournalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/capture'
    | '/dashboard'
    | '/learn'
    | '/settings'
    | '/tasks'
    | '/archive/$id'
    | '/archive/new'
    | '/journal/$id'
    | '/journal/new'
    | '/archive/'
    | '/journal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/capture'
    | '/dashboard'
    | '/learn'
    | '/settings'
    | '/tasks'
    | '/archive/$id'
    | '/archive/new'
    | '/journal/$id'
    | '/journal/new'
    | '/archive'
    | '/journal'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/capture'
    | '/_authenticated/dashboard'
    | '/_authenticated/learn'
    | '/_authenticated/settings'
    | '/_authenticated/tasks'
    | '/_authenticated/archive/$id'
    | '/_authenticated/archive/new'
    | '/_authenticated/journal/$id'
    | '/_authenticated/journal/new'
    | '/_authenticated/archive/'
    | '/_authenticated/journal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CaptureRoute: typeof CaptureRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/capture': {
      id: '/capture'
      path: '/capture'
      fullPath: '/capture'
      preLoaderRoute: typeof CaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learn': {
      id: '/_authenticated/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof AuthenticatedLearnRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/journal/': {
      id: '/_authenticated/journal/'
      path: '/journal'
      fullPath: '/journal/'
      preLoaderRoute: typeof AuthenticatedJournalIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/archive/': {
      id: '/_authenticated/archive/'
      path: '/archive'
      fullPath: '/archive/'
      preLoaderRoute: typeof AuthenticatedArchiveIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/journal/new': {
      id: '/_authenticated/journal/new'
      path: '/journal/new'
      fullPath: '/journal/new'
      preLoaderRoute: typeof AuthenticatedJournalNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/journal/$id': {
      id: '/_authenticated/journal/$id'
      path: '/journal/$id'
      fullPath: '/journal/$id'
      preLoaderRoute: typeof AuthenticatedJournalIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/archive/new': {
      id: '/_authenticated/archive/new'
      path: '/archive/new'
      fullPath: '/archive/new'
      preLoaderRoute: typeof AuthenticatedArchiveNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/archive/$id': {
      id: '/_authenticated/archive/$id'
      path: '/archive/$id'
      fullPath: '/archive/$id'
      preLoaderRoute: typeof AuthenticatedArchiveIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLearnRoute: typeof AuthenticatedLearnRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedArchiveIdRoute: typeof AuthenticatedArchiveIdRoute
  AuthenticatedArchiveNewRoute: typeof AuthenticatedArchiveNewRoute
  AuthenticatedJournalIdRoute: typeof AuthenticatedJournalIdRoute
  AuthenticatedJournalNewRoute: typeof AuthenticatedJournalNewRoute
  AuthenticatedArchiveIndexRoute: typeof AuthenticatedArchiveIndexRoute
  AuthenticatedJournalIndexRoute: typeof AuthenticatedJournalIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLearnRoute: AuthenticatedLearnRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedArchiveIdRoute: AuthenticatedArchiveIdRoute,
  AuthenticatedArchiveNewRoute: AuthenticatedArchiveNewRoute,
  AuthenticatedJournalIdRoute: AuthenticatedJournalIdRoute,
  AuthenticatedJournalNewRoute: AuthenticatedJournalNewRoute,
  AuthenticatedArchiveIndexRoute: AuthenticatedArchiveIndexRoute,
  AuthenticatedJournalIndexRoute: AuthenticatedJournalIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CaptureRoute: CaptureRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
